### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/mmj/w/CodeHub/codehub/secret.txt'

### ISSUE THREAD

**Issue by mm-sys-max** [CodeHub-Contributors/CodeHub#12]
سالام 
من این فایلو ساختم اما بازم ارور داد 
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by lnxpy** [comment]
Generate a new SECRET_KEY for your project. You have to paste it up inside `project/settings.py` file in `SECRET_KEY` variable which is empty by default.
