### ISSUE TITLE
Desktop Version

### ISSUE THREAD

**Issue by ghost1372** [CodeHub-Contributors/CodeHub#3]
سلام
تازه با سرویستون اشنا شدم و چون ای پی آی دارید به ذهنم اومد که نسخه دسکتاپ ویندوز رو با سی شارپ بنویسم 
اگر موافق باشید یه مخزن تو اکانت خودتون ایجاد کنید و با دادن دسترسی من روش کار کنم
ممنون

**Comment by lnxpy** [comment]
Hey Mahdi,

It's gonna be so good for CodeHub.
It is my pleasure to give this part to you. You just need to start the project on your local repository and develop it by yourself. I will check this out and fork it if you make it super naturally flexible and useful. :)

Good luck :heart:

**Comment by ashkan1375** [comment]
دادا چرا از سرور و دامین جدا استفاده نمی کنی؟
و چرا برای پروژه ارگان نمیسازی؟

**Comment by lnxpy** [comment]
Hey Ashkan,

It's in my schedule. I'll deploy CodeHub on a VPS soon. Just wanna make it better. This would happen after some optimizations.

CodeHub organization will be created soon and all CodeHub developers will be there. :) :heart:

**Comment by ghost1372** [comment]
Hi @lnxpy 
I created [CodeHubDesktop](https://github.com/ghost1372/CodeHubDesktop)

Features
- WPF .Net Core 3.1
- Self-Contained Exe
- Prism MVVM
- Multi Language (Dynamic language Change)
- Dark/Light/Violet Theme
- 2 type LeftMenu (I'm not sure I'll probably remove the modern menu in the future)
- Store Snippets in Sqlite (User Choice)
- Read Online Snippets with SID or Link

You can find the executable version [here](https://github.com/ghost1372/CodeHubDesktop/releases/tag/v1.0.0.0)

**Comment by lnxpy** [comment]
Hey Mahdi,

Such a WOW :heart_eyes:
It takes gut to do such a thing but you hit the head. :+1: :smiley: 
Though it's full of features, take a look at latest updates such as error field and so.
I'll make somewhere to interact to each other and work on CodeHub. :+1:

So joyful to hear from you. :)
 Nice job. Thanks.

**Comment by ghost1372** [comment]
tnx😁 @lnxpy 

Desktop Version is now [Updated ](https://github.com/ghost1372/CodeHubDesktop/releases/tag/v1.0.1.0) with Latest API

**Comment by lnxpy** [comment]
> tnxgrin @lnxpy
> 
> Desktop Version is now [Updated ](https://github.com/ghost1372/CodeHubDesktop/releases/tag/v1.0.1.0) with Latest API

Invitation has been sent to your account.
Welcome to [CodeHub Contributors Team](https://github.com/CodeHub-Contributors). :smiley:

Good luck. :heart:
